export {Button} from '../atoms/button/Button'
export {ViewAllButton} from '../atoms/button/ViewAllButton'
export {DownloadAppComponent} from '../atoms/card/DownloadAppComponent'
// export {FeaturedAcademyComponent} from '../atoms/card/FeaturedAcademyComponent'
// export {PopularAcademiesComponent} from '../atoms/card/PopularAcademiesComponent'
// export {PopularAcademiesPersonalities} from '../atoms/card/PopularAcademiesPersonalities'
// export {PopularCategoriesCard} from '../atoms/card/PopularCategoriesCard'
// export {PopularCitiesComponent} from '../atoms/card/PopularCitiesComponent'
// export {UpcomingEventsComponent} from '../atoms/card/UpcomingEventsComponent'
// export {Heart} from '../atoms/heart/Heart'
// // export {HorizontalLine} from '../atoms/horizontalline'
// export {SocialMediaIcons} from '../atoms/socialmediaicons/SocialMediaIcons'
