export {FeauturedAcademies} from '../molecules/FeauturedAcadamies'
export {PopularCities} from '../molecules/PopularCities'
export {PopularAcademies} from '../molecules/PopularAcademies'
export {UpcomingEvents} from '../molecules/UpcomingEvents'
export {PopularPersonalities} from '../molecules/PopularPersonalities'
